// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebProject.Data;

namespace WebProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220531085104_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebProject.Models.City", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CountryID");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            ID = new Guid("c6dd1263-f7cb-4f24-9a4c-86f4009674c1"),
                            CountryID = new Guid("14b0821e-fd60-4817-bab6-75be489848bd"),
                            Name = "Los Angeles"
                        },
                        new
                        {
                            ID = new Guid("efbb7f0e-ade1-4458-bfb5-b179298d8fcf"),
                            CountryID = new Guid("14b0821e-fd60-4817-bab6-75be489848bd"),
                            Name = "Chicago"
                        },
                        new
                        {
                            ID = new Guid("3f0271fb-1675-40e0-b7a3-50f97e06f45e"),
                            CountryID = new Guid("14b0821e-fd60-4817-bab6-75be489848bd"),
                            Name = "Springfield"
                        },
                        new
                        {
                            ID = new Guid("b9a8b919-c7af-4e23-bf20-4ca5ccf6258e"),
                            CountryID = new Guid("a0f82d3f-6543-448c-bbb3-d5e5b5ffaea9"),
                            Name = "Dreamland"
                        },
                        new
                        {
                            ID = new Guid("a8e2737b-bec9-4d54-af91-fc77cb71a932"),
                            CountryID = new Guid("fe47740f-b727-4605-89ab-cc9ff71f9a03"),
                            Name = "Borås"
                        },
                        new
                        {
                            ID = new Guid("49daa98f-768e-44d7-8c72-00341d6ecddf"),
                            CountryID = new Guid("14b0821e-fd60-4817-bab6-75be489848bd"),
                            Name = "Albuquerque"
                        });
                });

            modelBuilder.Entity("WebProject.Models.Country", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            ID = new Guid("fe47740f-b727-4605-89ab-cc9ff71f9a03"),
                            Name = "Sweden"
                        },
                        new
                        {
                            ID = new Guid("a0f82d3f-6543-448c-bbb3-d5e5b5ffaea9"),
                            Name = "Germany"
                        },
                        new
                        {
                            ID = new Guid("14b0821e-fd60-4817-bab6-75be489848bd"),
                            Name = "USA"
                        });
                });

            modelBuilder.Entity("WebProject.Models.Person", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CityID");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            ID = new Guid("e27c4995-5430-4bb4-8489-74eff4d69761"),
                            CityID = new Guid("c6dd1263-f7cb-4f24-9a4c-86f4009674c1"),
                            Name = "Jane Doe",
                            PhoneNumber = "555-123 45"
                        },
                        new
                        {
                            ID = new Guid("160aabb1-5799-43b9-9774-3249992441c9"),
                            CityID = new Guid("efbb7f0e-ade1-4458-bfb5-b179298d8fcf"),
                            Name = "John Doe",
                            PhoneNumber = "555-123 45"
                        },
                        new
                        {
                            ID = new Guid("e846f52c-ac1e-42c2-9900-f5b37f0b2c3f"),
                            CityID = new Guid("3f0271fb-1675-40e0-b7a3-50f97e06f45e"),
                            Name = "Marge Simpson",
                            PhoneNumber = "939-555-0113"
                        },
                        new
                        {
                            ID = new Guid("9490db50-9448-477e-acc4-b9a095cdec56"),
                            CityID = new Guid("b9a8b919-c7af-4e23-bf20-4ca5ccf6258e"),
                            Name = "Somna Sculpt",
                            PhoneNumber = "1-555-766728578"
                        },
                        new
                        {
                            ID = new Guid("03b39f07-6712-42b9-a004-40db45cbed73"),
                            CityID = new Guid("a8e2737b-bec9-4d54-af91-fc77cb71a932"),
                            Name = "Anthony Hopkins",
                            PhoneNumber = "555-6162"
                        },
                        new
                        {
                            ID = new Guid("c0c9982d-b27a-4118-80c2-b69d6367f277"),
                            CityID = new Guid("49daa98f-768e-44d7-8c72-00341d6ecddf"),
                            Name = "Saul Goodman",
                            PhoneNumber = "505-842-5662"
                        });
                });

            modelBuilder.Entity("WebProject.Models.City", b =>
                {
                    b.HasOne("WebProject.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebProject.Models.Person", b =>
                {
                    b.HasOne("WebProject.Models.City", "City")
                        .WithMany("Citizens")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
