// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebProject.Data;

namespace WebProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebProject.Models.Person", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            ID = new Guid("ca92bb42-3f87-4cc9-9c0c-2efe3b6a0046"),
                            City = "Los Angeles",
                            Name = "Jane Doe",
                            PhoneNumber = "555-123 45"
                        },
                        new
                        {
                            ID = new Guid("c88b0434-a202-4e35-a85c-3a6aad549098"),
                            City = "Chicago",
                            Name = "John Doe",
                            PhoneNumber = "555-123 45"
                        },
                        new
                        {
                            ID = new Guid("903f249d-1976-4f9e-a048-be14c72a74d2"),
                            City = "Kansas",
                            Name = "Janelle Monáe",
                            PhoneNumber = "555-5555"
                        },
                        new
                        {
                            ID = new Guid("39c5a1c9-0fd2-431d-bea6-57d99c7c7e3d"),
                            City = "Springfield",
                            Name = "Marge Simpson",
                            PhoneNumber = "939-555-0113"
                        },
                        new
                        {
                            ID = new Guid("5f018729-3ae0-494c-8514-29f5a8f11160"),
                            City = "Dreamland",
                            Name = "Somna Sculpt",
                            PhoneNumber = "1-555-766728578"
                        },
                        new
                        {
                            ID = new Guid("83779862-0eea-4f50-9ed9-8655a56e7265"),
                            City = "Pittsburgh",
                            Name = "Anthony Hopkins",
                            PhoneNumber = "555-6162"
                        },
                        new
                        {
                            ID = new Guid("edda6d7e-0f99-4cf3-a1d5-35de1d10bec0"),
                            City = "Albuquerque",
                            Name = "Saul Goodman",
                            PhoneNumber = "505-842-5662"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
